Test/ask question
coding-bootcamps-eu/ama-tool pull request #31
Opened 2021-08-25 10:39 UTC by EeveeInGaa

please to not merge jet, because we nee to add tests. just for first review

2021-08-26 06:56 UTC, robinboehm requested changes
Please adjust some smaller changes. Everything else looks really good <3

2021-08-26 06:56 UTC, robinboehm commented on tests/e2e/specs/AskQuestion.js
> +      .first()
Please use an explicit selector instead of "first" and "last" it could break very easily when changing something on the layout. Better use a selector that matches only the element that you want to select

2021-08-26 06:56 UTC, robinboehm commented on tests/e2e/specs/AskQuestion.js
> +  it("Preview button should be clickable and get toggled", () => {
Please add a test that tests if the preview appears

2021-08-26 06:56 UTC, robinboehm commented on src/components/AskQuestion/AskQuestion.vue
> +        data-cy="input-text"
Like that you used `data-cy`.
Don't like that you form classes for element groups instead of clear identifications for each button e.g. `input-text-title` ... in my opinion it would make the test more robust for changes

2021-08-26 06:56 UTC, robinboehm commented on tests/e2e/specs/AskQuestion.js
> +    cy.get("[data-cy='input-text']").last().focus();
What happens when it's not focusable? Does the test fail?
Here is no should or something else ... don't know how to define a should for that.

But: If the test never fails it's useless =)

2021-08-26 06:56 UTC, robinboehm commented on tests/e2e/specs/AskQuestion.js
> +        "# Test typing in question description..{backspace}{enter}{enter}*Hello World!*{enter}Test text."
Where is the assert that checks if the text is accepted?

2021-08-26 08:03 UTC, EeveeInGaa commented on tests/e2e/specs/AskQuestion.js
> +      .first()
changed the data-cy in askQuestion component, its super specific now

2021-08-26 08:05 UTC, EeveeInGaa commented on src/components/AskQuestion/AskQuestion.vue
> +        data-cy="input-text"
specified data-cy, works perfectly with the removal of .first() and .last()

2021-08-26 08:28 UTC, EeveeInGaa commented on tests/e2e/specs/AskQuestion.js
> +  it("Preview button should be clickable and get toggled", () => {
added test if the markdown preview appears, just haven't seen it yesterday

2021-08-26 08:43 UTC, EeveeInGaa commented on tests/e2e/specs/AskQuestion.js
> +    cy.get("[data-cy='input-text']").last().focus();
I don't know how an element should not be focusable, because its in focus the time we click it or hit tab and how it should be tested.
But I understand that the test is useless if there is no "negative" case

2021-08-26 08:46 UTC, EeveeInGaa commented on tests/e2e/specs/AskQuestion.js
> +        "# Test typing in question description..{backspace}{enter}{enter}*Hello World!*{enter}Test text."
What do you mean by that? If I click it i can type text or do you mean markdown?

2021-08-26 10:01 UTC, EeveeInGaa commented on tests/e2e/specs/AskQuestion.js
> +    cy.get("[data-cy='input-text']").last().focus();
I removed the test. first tested if the test fails when I remove the focus-option (tabindex="-1") but the test still succeeded, so yes, it was an unnecessary test. Unfortunately cypress offers no other option to test the focus yet. (the physical "Tab"-key can't be tested)

2021-08-26 10:03 UTC, EeveeInGaa commented on tests/e2e/specs/AskQuestion.js
> +        "# Test typing in question description..{backspace}{enter}{enter}*Hello World!*{enter}Test text."
I commented why this test is needed. Its in preparation for the test to send to the database (shouldnt send if nothing is typed) and it is needed to test the markdown function and if the preview works correctly.

2021-08-30 11:41 UTC, robinboehm requested changes
Please merge after finishing last few changes =)

2021-08-30 11:41 UTC, robinboehm commented on tests/e2e/specs/AskQuestion.js
> +      "https://ama-tool-ea7e0-default-rtdb.europe-west1.firebasedatabase.app",
Kann dies auch ein Regex oder wildcard sein? Also Situation: Wir ziehen die Firebase in einen offiziellen Firebase Bootcamp Account und die URL ändert sich leicht.

2021-08-30 11:41 UTC, robinboehm commented on tests/e2e/specs/AskQuestion.js
> +    cy.get("[data-cy='send-button']").click();
You could check for url if it's e.g. on the list page after this.

2021-08-31 12:35 UTC, merged